@echo off
REM fastReader wrapper (Windows). Thin dispatcher:
REM   load|toc|get|search -> python -m fastReader.<cmd> (PYTHONPATH auto-set)
REM   json               -> pass-through to the quick-json-reader binary
REM                         when the sibling skill is installed
REM All human-readable help text lives in:
REM   wrapper_help_json_on.txt
REM   wrapper_help_json_off.txt
REM so that .sh and .bat share one source of truth and stay in sync.

SETLOCAL ENABLEDELAYEDEXPANSION

SET "FAST_READER_WRAPPER_SCRIPT_DIR=%~dp0"
SET "FAST_READER_WRAPPER_SCRIPT_DIR=%FAST_READER_WRAPPER_SCRIPT_DIR:~0,-1%"
FOR %%I IN ("%FAST_READER_WRAPPER_SCRIPT_DIR%") DO SET "FAST_READER_SKILL_PARENT_DIR=%%~dpI"
SET "FAST_READER_SKILL_PARENT_DIR=%FAST_READER_SKILL_PARENT_DIR:~0,-1%"

SET "FAST_READER_DEFAULT_JSON_BIN_PATH=%FAST_READER_SKILL_PARENT_DIR%\quick-json-reader\quick-json-reader.exe"
IF NOT DEFINED FAST_READER_JSON_BIN SET "FAST_READER_JSON_BIN=%FAST_READER_DEFAULT_JSON_BIN_PATH%"

SET "FAST_READER_JSON_MODULE_AVAILABLE=0"
IF EXIST "%FAST_READER_JSON_BIN%" SET "FAST_READER_JSON_MODULE_AVAILABLE=1"

IF "%~1"=="" GOTO SHOW_HELP
IF /I "%~1"=="-h" GOTO SHOW_HELP
IF /I "%~1"=="--help" GOTO SHOW_HELP

SET "FAST_READER_SUBCOMMAND_NAME=%~1"
SHIFT

IF /I "%FAST_READER_SUBCOMMAND_NAME%"=="load"   GOTO DISPATCH_PY
IF /I "%FAST_READER_SUBCOMMAND_NAME%"=="toc"    GOTO DISPATCH_PY
IF /I "%FAST_READER_SUBCOMMAND_NAME%"=="get"    GOTO DISPATCH_PY
IF /I "%FAST_READER_SUBCOMMAND_NAME%"=="search" GOTO DISPATCH_PY
IF /I "%FAST_READER_SUBCOMMAND_NAME%"=="json"   GOTO DISPATCH_JSON

ECHO fastReader: unknown subcommand '%FAST_READER_SUBCOMMAND_NAME%' 1>&2
CALL :PRINT_HELP 1>&2
EXIT /B 2

:SHOW_HELP
CALL :PRINT_HELP
EXIT /B 0

:PRINT_HELP
IF "%FAST_READER_JSON_MODULE_AVAILABLE%"=="1" (
    TYPE "%FAST_READER_WRAPPER_SCRIPT_DIR%\wrapper_help_json_on.txt"
) ELSE (
    TYPE "%FAST_READER_WRAPPER_SCRIPT_DIR%\wrapper_help_json_off.txt"
)
GOTO :EOF

:DISPATCH_PY
SET "FAST_READER_FORWARDED_ARGS="
:ARG_LOOP_PY
IF "%~1"=="" GOTO RUN_PYTHON
SET "FAST_READER_FORWARDED_ARGS=%FAST_READER_FORWARDED_ARGS% %1"
SHIFT
GOTO ARG_LOOP_PY

:RUN_PYTHON
SET "PYTHONPATH=%FAST_READER_SKILL_PARENT_DIR%"
python -m fastReader.%FAST_READER_SUBCOMMAND_NAME%%FAST_READER_FORWARDED_ARGS%
EXIT /B %ERRORLEVEL%

:DISPATCH_JSON
IF "%FAST_READER_JSON_MODULE_AVAILABLE%"=="0" (
    ECHO fastReader: the 'json' module requires the quick-json-reader skill. 1>&2
    ECHO Expected binary at: %FAST_READER_JSON_BIN% 1>&2
    ECHO Install the quick-json-reader skill alongside fastReader, or set 1>&2
    ECHO FAST_READER_JSON_BIN to an absolute path to the binary. 1>&2
    EXIT /B 3
)
SET "FAST_READER_JSON_FORWARDED_ARGS="
:ARG_LOOP_JSON
IF "%~1"=="" GOTO RUN_JSON
SET "FAST_READER_JSON_FORWARDED_ARGS=%FAST_READER_JSON_FORWARDED_ARGS% %1"
SHIFT
GOTO ARG_LOOP_JSON

:RUN_JSON
"%FAST_READER_JSON_BIN%"%FAST_READER_JSON_FORWARDED_ARGS%
EXIT /B %ERRORLEVEL%
